FROM node:22-alpine
WORKDIR /app

RUN apk add --no-cache libc6-compat python3 make g++ \
	&& corepack enable

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --shamefully-hoist

EXPOSE 3001
ENV PORT=3001 NEXT_TELEMETRY_DISABLED=1

CMD ["pnpm", "run", "dev"]
